# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9467f9ffafef82f24db4817d2e0d54c82614adeb8d560d777505dffa877a94693d514edaa9e1f335c364ed3e3ae4236f26ec66e27fd53ae19a4d7c09fa13cfb2

test:
  secret_key_base: 29310d44d04c0e58a56018a4941887905a71ea1b178f8124c9b39e5e4dcf8018c318bc0eb22187c201f5a27601e6d75eaee3282ee924d35abc4da4cfcb93f00a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
